config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'

  resources :instructors
  resources :topics
  resources :problems

  get '/help',  to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/signup',  to: 'instructors#activate'
  post  '/signup',  to: 'instructors#update_activate'
  patch  '/signup',  to: 'instructors#update_activate'
  get  '/create_instructor',  to: 'instructors#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/new_topic', to: 'topics#new'
  get '/new_problem', to: 'problems#new'
  # post '/new_topic', to: 'topics#create'


  get '/quiz', to: 'problem_displays#quiz'
  post '/quiz', to: 'problem_displays#selected'


  get '/quiz_problem', to: 'problem_displays#quiz_problem'
  post '/quiz_problem', to: 'problem_displays#save_answer'
  get '/quiz_problem_answer', to: 'problem_displays#quiz_problem_answer'
  get '/quiz_flashcard_question', to: 'problem_displays#quiz_flashcard_question'
  get '/quiz_flashcard_answer', to: 'problem_displays#quiz_flashcard_answer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :problems, dependent: :destroy
  validates :name, presence:   true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    before_action :logged_in_instructor, only: [:new, :create, :show, :edit, :update, :index, :destroy]
  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      log_in @topic
      flash[:success] = "Create topic successfully."
      redirect_to @topic
    else
      render 'new'
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @problems = @topic.problems.paginate(page: params[:page], :per_page =>10)
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      flash[:success] = "Topic updated."
      redirect_to @topic
    else
      render 'edit'
    end
  end

  def index
    @topics = Topic.paginate(page: params[:page], :per_page =>10)
  end

  def destroy
    Topic.find(params[:id]).destroy
    flash[:success] = "Topic deleted."
    redirect_to topics_url
  end

  private

  def topic_params
    params.require(:topic).permit(:name)
  end

  def instructor_params
    params.require(:instructor).permit(:name, :email, :password,
                                       :password_confirmation)
  end

  def logged_in_instructor
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_instructor
    @instructor = Instructor.find(params[:id])
    redirect_to(root_url) unless current_instructor?(@instructor)
  end

  def admin_instructor
    redirect_to(root_url) unless current_instructor.admin?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
  <%= render 'shared/error_messages_topic', object: @topic %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/topics/_topic.html.erb
<li>
  <ul class="ul_two">
    <li><%= link_to topic.name, topic %></li>
    <li><%= link_to "Edit", edit_topic_path(topic) %></li>
    <li><%= link_to "Delete", topic, method: :delete,
                    data: {confirm: "Are you sure to delete this topic?"} %></li>
  </ul> 
</li>

app/views/topics/edit.html.erb
<% provide(:title, "Edit topic") %>
<% provide(:button_text, 'Save changes') %>

<h1>Update topic</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<% provide(:title, 'All Topics') %>
<h1>All topics</h1>

<h2><%= link_to "Create New Topic", new_topic_path %></h2>

<%= will_paginate %>

<ul class="topics">
  <% @topics.each do |topic| %>
    <%= render topic %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/topics/new.html.erb
<% provide(:title, 'Create Topic') %>
<% provide(:button_text, 'Create Topic') %>

<h1>Create Topic</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<% provide(:title, @topic.name) %>
<div class="row">
  <aside class="col-md-3">
    <section class="topic_info">
      <h1>
        <%= @topic.name %>
      </h1>

      <h2><%= link_to "Edit Topic", edit_topic_path(@topic)%></h2>

      <h2><%= link_to "Create New Problem", new_problem_path(:topic_from => @topic.id)%></h2>

      <h2><%= link_to "View All Topics", topics_path %></h2>
    </section>
  </aside>

  <div class="col-md-9">
    <h3>Problems (<%= @topic.problems.count %>)</h3>
    <% if @topic.problems.any? %>
      <ol class="problems">
        <%= render @problems %>
      </ol>
      <%= will_paginate @problems %>
    <% end %>
  </div>
</div>