config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'

  resources :instructors
  resources :topics
  resources :problems

  get '/help',  to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/signup',  to: 'instructors#activate'
  post  '/signup',  to: 'instructors#update_activate'
  patch  '/signup',  to: 'instructors#update_activate'
  get  '/create_instructor',  to: 'instructors#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/new_topic', to: 'topics#new'
  get '/new_problem', to: 'problems#new'
  # post '/new_topic', to: 'topics#create'


  get '/quiz', to: 'problem_displays#quiz'
  post '/quiz', to: 'problem_displays#selected'


  get '/quiz_problem', to: 'problem_displays#quiz_problem'
  post '/quiz_problem', to: 'problem_displays#save_answer'
  get '/quiz_problem_answer', to: 'problem_displays#quiz_problem_answer'
  get '/quiz_flashcard_question', to: 'problem_displays#quiz_flashcard_question'
  get '/quiz_flashcard_answer', to: 'problem_displays#quiz_flashcard_answer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:   true, length: { maximum: 255 },
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = Instructor.new_token
    update_attribute(:remember_digest, Instructor.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :logged_in_instructor, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  before_action :correct_instructor,   only: [:edit, :update]
  before_action :admin_instructor,     only: [:new, :create, :destroy]

  def create
    @instructor = Instructor.new(instructor_params_create)
    @instructor.activated = false
    @instructor.password = "000000"
    @instructor.password_confirmation = "000000"
    if @instructor.save
      flash[:success] = "Create new instructor successfully."
      redirect_to @instructor
    else
      render 'new'
    end
  end

  def index
    @instructors = Instructor.paginate(page: params[:page], :per_page =>10)
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(params[:id])
    if @instructor.update_attributes(instructor_params)
      flash[:success] = "Profile updated."
      redirect_to @instructor
    else
      render 'edit'
    end
  end

  def destroy
    Instructor.find(params[:id]).destroy
    flash[:success] = "Instructor deleted."
    redirect_to instructors_url
  end

  def activate
    @instructor = Instructor.new
  end

  def update_activate
    @instructors = Instructor.where({ email: params[:instructor][:email].downcase })
    if(@instructors.size == 0)
      @instructor = Instructor.new
      flash[:danger] = "Not eligible for signing up."
      redirect_to signup_url
    else
      @instructor = @instructors[0]
      if @instructor.activated
        flash[:danger] = "You have already signed up."
        redirect_to signup_url
      else
        @instructor.activated = true
        if @instructor.update_attributes(instructor_params)
          log_in @instructor
          flash[:success] = "Account Activated."
          redirect_to @instructor
        else
          render 'activate'
        end
      end
    end
  end

  private

  def instructor_params_create
    params.require(:instructor).permit(:name, :email, :admin)
  end

  def instructor_params
    params.require(:instructor).permit(:name, :email, :password,
                                       :password_confirmation, :admin)
  end

  def logged_in_instructor
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_instructor
    @instructor = Instructor.find(params[:id])
    redirect_to(root_url) unless current_instructor?(@instructor)
  end

  def admin_instructor
    redirect_to(root_url) unless current_instructor.admin?
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <%= render 'shared/error_messages_instructor', object: @instructor %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/instructors/_instructor.html.erb
<li>
  <ul class="ul_five">
    <li style="width:30%"><%= link_to instructor.name, instructor %></li>
    <li style="width:30%"><%= link_to instructor.email, "mailto:" + instructor.email %></li>
    <li style="width:15%"> <% if instructor.admin %>
        Administrator
      <% end %></li>
    <li style="width:15%">
      <% if !instructor.activated %>
        Not Activated
      <% end %></li>
    <li style="width:10%"> <% if current_instructor.admin? && !current_instructor?(instructor) %>
        <%= link_to "delete", instructor, method: :delete,
                    data: { confirm: "Are you sure to delete the instructor?" } %>
      <% end %></li>
  </ul>
</li>

app/views/instructors/activate.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create My Account') %>

<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @instructor, url: {action: "update_activate"} do |f| %>
      <%= render 'shared/error_messages_instructor', object: @instructor %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/instructors/edit.html.erb
<% provide(:title, "Edit instructor") %>
<% provide(:button_text, 'Save Changes') %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/instructors/index.html.erb
<% provide(:title, 'Instructors') %>
<h1>All instructors</h1>

<% if current_instructor.admin? %>
  <h2><%= link_to "Add New Instructor", create_instructor_path %></h2>
<% end %>

<%= will_paginate %>

<ul class="instructors">
  <% @instructors.each do |instructor| %>
    <%= render instructor %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/instructors/new.html.erb
<% provide(:title, 'Add Instructor') %>
<% provide(:button_text, 'Add New Instructor') %>

<h1>Add New Instructor</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@instructor) do |f| %>
      <%= render 'shared/error_messages_instructor', object: @instructor %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :admin, class: "checkbox inline" do %>
        <%= f.check_box :admin %>
        <span>Administrator</span>
      <% end %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/instructors/show.html.erb
<% provide(:title, @instructor.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="instructor_info">
      <h1>
        <%= @instructor.name %>
      </h1>
      <div class = "instructorview">
      <div><%= link_to @instructor.email, "mailto:" + @instructor.email %></div>
      <div> <% if @instructor.admin %>
          Administrator
          <% else %>
          Normal User
        <% end %></div>
      <div>
        <% if !@instructor.activated %>
          Not Activated
        <% else %>
        Activated
        <% end %></div>
      </div>
    </section>
  </aside>
</div>