config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'

  resources :instructors
  resources :topics
  resources :problems

  get '/help',  to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/signup',  to: 'instructors#activate'
  post  '/signup',  to: 'instructors#update_activate'
  patch  '/signup',  to: 'instructors#update_activate'
  get  '/create_instructor',  to: 'instructors#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/new_topic', to: 'topics#new'
  get '/new_problem', to: 'problems#new'
  # post '/new_topic', to: 'topics#create'


  get '/quiz', to: 'problem_displays#quiz'
  post '/quiz', to: 'problem_displays#selected'


  get '/quiz_problem', to: 'problem_displays#quiz_problem'
  post '/quiz_problem', to: 'problem_displays#save_answer'
  get '/quiz_problem_answer', to: 'problem_displays#quiz_problem_answer'
  get '/quiz_flashcard_question', to: 'problem_displays#quiz_flashcard_question'
  get '/quiz_flashcard_answer', to: 'problem_displays#quiz_flashcard_answer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/controllers/problem_displays_controller.rb
class ProblemDisplaysController < ApplicationController
  def quiz
    @topics = Topic.all
  end

  def selected
    session[:topics] = params[:selected].select{|k,v| v=='1'}.keys.map{|v| v}
    session[:problems] = session[:topics].map{|v| Topic.find(v).problems.map{|w| w.id}}.flatten(1)
    session[:quiz_type] = params[:selected][:quiz_type]

    session[:current_problem] = 0


    if(session[:problems].size == 0)

    end

    if(session[:quiz_type] == "Flashcard")
      redirect_to(quiz_flashcard_question_url)
    else
      session[:answers] = Array.new(session[:problems].size,"")
      redirect_to(quiz_problem_url)
    end
  end

  def quiz_problem

    if(params[:nextid])
      @thisid = params[:nextid].to_i
    else
      @thisid = 0
    end
    session[:current_problem] = @thisid
    @lastanswer =  session[:answers][@thisid]

    @problem = Problem.find(session[:problems][@thisid])
  end

  def quiz_problem_answer

    if(params[:nextid])
      @thisid = params[:nextid].to_i
    else
      @thisid = 0
    end
    session[:current_problem] = @thisid
    @lastanswer =  session[:answers][@thisid]

    @problem = Problem.find(session[:problems][@thisid])
  end

  def save_answer
    @thisid = session[:current_problem]
    session[:answers][@thisid] = params[:student][:answer]
    @lastanswer =  session[:answers][@thisid]
    @problem = Problem.find(session[:problems][@thisid])
    render 'quiz_problem'
  end

  def quiz_flashcard_question
    if(params[:nextid])
      @thisid = params[:nextid].to_i
    else
      @thisid = 0
    end
    @problem = Problem.find(session[:problems][@thisid])
  end

  def quiz_flashcard_answer
    if(params[:nextid])
      @thisid = params[:nextid].to_i
    else
      @thisid = 0
    end
    @problem = Problem.find(session[:problems][@thisid])
  end

end

app/helpers/problem_displays_helper.rb
module ProblemDisplaysHelper
end

app/views/problem_displays/quiz.html.erb
<% provide(:title, "Select Topics") %>
<h1>Select Topics</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:selected) do |f| %>

      <%= f.label "Topics"%>

      <% @topics.each do |topic| %>
        <%= f.label topic.id, class: "checkbox inline" do %>
          <%= f.check_box topic.id, {:checked=>true}, '1', '0' %>
          <span><%=topic.name%></span>
        <% end %>
      <% end %>
      <%= f.label :quiz_type%>
        <%= f.collection_select  :quiz_type, ["Quiz","Flashcard"], :to_s, :to_s%>


      <%= f.submit "Select Topics", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/problem_displays/quiz_flashcard_answer.html.erb
<% provide(:title, "Problem " + (@thisid+1).to_s) %>
<h1><%= "Problem " + (@thisid+1).to_s + "/" + session[:problems].size.to_s %></h1>
<div class="row">
  <aside class="col-md-12">
    <section class="problem_info">
      <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML' async></script>
      <h1>Problem Topic: </h1>
      <div class="problemview"><%= @problem.topic.name%></div>

      <h1>Question: </h1>
      <div class="problemview"><%= simple_format(@problem.question) %></div>

      <h1>Answer: </h1>
      <div class="problemview"><%= simple_format(@problem.answer) %></div>

      <h1>Remark: </h1>
      <div class="problemview"><%= simple_format(@problem.remark) %></div>

      <div>
        <%= link_to "Hide Answer", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary", style: "width:100%" %>
      </div>
      <div class = "buttons">
        <% if (@thisid==0) %>
          <%= link_to "Previous Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid) , class: "btn btn-primary" , style: "width:20%"%>
        <% else %>
          <%= link_to "Previous Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid - 1), class: "btn btn-primary", style: "width:20%" %>
        <% end %>
        <% if (@thisid==session[:problems].size-1) %>
          <%= link_to "Next Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary" , style: "width:20%;float:right"%>
        <% else %>
          <%= link_to "Next Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid + 1), class: "btn btn-primary", style: "width:20%;float:right" %>
        <% end %>
      </div>
      <div>
        <%= link_to "Quit Evaluation", root_path , class: "btn btn-primary" %>
      </div>

    </section>
  </aside>
</div>

app/views/problem_displays/quiz_flashcard_question.html.erb
<% provide(:title, "Problem " + (@thisid+1).to_s) %>
<h1><%= "Problem " + (@thisid+1).to_s + "/" + session[:problems].size.to_s%></h1>
<div class="row">
  <aside class="col-md-12">
    <section class="problem_info">
      <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML' async></script>
      <h1>Problem Topic: </h1>
      <div class="problemview"><%= @problem.topic.name%></div>

      <h1>Question: </h1>
      <div class="problemview"><%= simple_format(@problem.question) %></div>


      <div>
        <%= link_to "Show Answer", quiz_flashcard_answer_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary", style: "width:100%" %>
      </div>
      <div class = "buttons">
        <% if (@thisid==0) %>
          <%= link_to "Previous Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid) , class: "btn btn-primary", style: "width:20%" %>
        <% else %>
          <%= link_to "Previous Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid - 1), class: "btn btn-primary", style: "width:20%" %>
        <% end %>
        <% if (@thisid==session[:problems].size-1) %>
          <%= link_to "Next Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary" , style: "width:20%;float:right" %>
        <% else %>
          <%= link_to "Next Problem", quiz_flashcard_question_path(:thisid => @thisid, :nextid => @thisid + 1), class: "btn btn-primary", style: "width:20%;float:right" %>
        <% end %>
      </div>
      <div>
        <%= link_to "Quit Evaluation", root_path , class: "btn btn-primary", style: "width:20%" %>
      </div>


    </section>
  </aside>
</div>

app/views/problem_displays/quiz_problem.html.erb
<% provide(:title, "Problem "+(@thisid+1).to_s) %>
<h1><%= "Problem " + (@thisid+1).to_s + "/" + session[:problems].size.to_s %></h1>
<div class="row">
  <aside class="col-md-12">
    <section class="problem_info">
      <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML' async></script>

      <h1>Problem Topic: </h1>
      <div class="problemview"><%= @problem.topic.name%></div>

      <h1>Question: </h1>
      <div class = "problemview"><%= simple_format(@problem.question) %></div>

      <%= form_for(:student) do |f| %>
        <h1>Your Answer: </h1>
        <%= f.text_area :answer, :value => @lastanswer %>
        <%= f.submit "Save Your Answer", class: "btn btn-primary"%>
      <% end %>

      <div class = "buttons">
        <% if (@thisid==0) %>
          <%= link_to "Previous Problem", quiz_problem_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary", style: "width:20%" %>
        <% else %>
          <%= link_to "Previous Problem", quiz_problem_path(:thisid => @thisid, :nextid => @thisid - 1) , class: "btn btn-primary", style: "width:20%"  %>
        <% end %>
        <% if (@thisid==session[:problems].size-1) %>
          <%= link_to "Next Problem", quiz_problem_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary", style: "width:20%;float:right"  %>
        <% else %>
          <%= link_to "Next Problem", quiz_problem_path(:thisid => @thisid, :nextid => @thisid + 1), class: "btn btn-primary", style: "width:20%;float:right"  %>
        <% end %>
      </div>

      <div>
        <%= link_to "Finish Evaluation", quiz_problem_answer_path , class: "btn btn-primary", style: "width:20%"  %>
      </div>


    </section>
  </aside>
</div>



app/views/problem_displays/quiz_problem_answer.html.erb
<% provide(:title, "Problem " + (@thisid+1).to_s) %>
<h1><%= "Problem " + (@thisid+1).to_s + "/" + session[:problems].size.to_s %></h1>
<div class="row">
  <aside class="col-md-12">
    <section class="problem_info">
      <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/latest.js?config=TeX-MML-AM_CHTML' async></script>

      <h1>Problem Topic: </h1>
      <div class="problemview"><%= @problem.topic.name%></div>

      <h1>Question: </h1>
      <div class="problemview"><%= simple_format(@problem.question) %></div>

      <h1>Answer: </h1>
      <div class="problemview"><%= simple_format(@problem.answer) %></div>

      <h1>Your Answer: </h1>
      <div class="problemview"><%= @lastanswer %></div>

      <h1>Remark: </h1>
      <div class="problemview"><%= simple_format(@problem.remark) %></div>

      <div class = "buttons">
        <% if (@thisid == 0) %>
          <%= link_to "Previous Problem", quiz_problem_answer_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary", style: "width:20%"  %>
        <% else %>
          <%= link_to "Previous Problem", quiz_problem_answer_path(:thisid => @thisid, :nextid => @thisid - 1), class: "btn btn-primary", style: "width:20%"  %>
        <% end %>
        <% if (@thisid == session[:problems].size - 1) %>
          <%= link_to "Next Problem", quiz_problem_answer_path(:thisid => @thisid, :nextid => @thisid), class: "btn btn-primary", style: "width:20%;float:right"  %>
        <% else %>
          <%= link_to "Next Problem", quiz_problem_answer_path(:thisid => @thisid, :nextid => @thisid + 1), class: "btn btn-primary", style: "width:20%;float:right"  %>
        <% end %>
      </div>
      <div>
        <%= link_to "Quit Evaluation", root_path, class: "btn btn-primary", style: "width:20%" %>
      </div>


    </section>
  </aside>
</div>