config/routes.rb
Rails.application.routes.draw do
  
  get 'topics/new'

  resources :instructors
  resources :topics
  resources :problems

  get '/help',  to: 'static_pages#help'
  get '/about',  to: 'static_pages#about'
  get  '/contact',  to: 'static_pages#contact'
  get  '/signup',  to: 'instructors#activate'
  post  '/signup',  to: 'instructors#update_activate'
  patch  '/signup',  to: 'instructors#update_activate'
  get  '/create_instructor',  to: 'instructors#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/new_topic', to: 'topics#new'
  get '/new_problem', to: 'problems#new'
  # post '/new_topic', to: 'topics#create'


  get '/quiz', to: 'problem_displays#quiz'
  post '/quiz', to: 'problem_displays#selected'


  get '/quiz_problem', to: 'problem_displays#quiz_problem'
  post '/quiz_problem', to: 'problem_displays#save_answer'
  get '/quiz_problem_answer', to: 'problem_displays#quiz_problem_answer'
  get '/quiz_flashcard_question', to: 'problem_displays#quiz_flashcard_question'
  get '/quiz_flashcard_answer', to: 'problem_displays#quiz_flashcard_answer'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Team Froyo
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CSCE 625", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Questions <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View Topics", topics_path %></li>
              <li><%= link_to "View Problems", problems_path %></li>
            </ul>
          </li>
          <li><%= link_to "Instructors", instructors_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_instructor %></li>
              <li><%= link_to "Settings", edit_instructor_path(current_instructor) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Instructor log in", login_path %></li>
        <% end %>
        <li><%= link_to "Help", help_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= favicon_link_tag image_path("tamu.png") %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>